services:
  mysql:
    image: mysql:8
    container_name: employee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    image: kimadcy/employee_management-backend:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: employee_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql

  frontend:
    image: kimadcy/employee_management-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:

