version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: db
      MYSQL_PASSWORD: dbpass
    ports:
      - "3307:3306"
    networks:
      - employee-network

  app:
    image: my-employee-app:1.0
    container_name: employee-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: db
      SPRING_DATASOURCE_PASSWORD: dbpass
    ports:
      - "8080:8080"
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge
